# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 47fd2668b9820499e89c0249b59bc3a1918de7b63bdd0ab81c5259b4bf76adb5fb5bfd8d9aa4eb0680a948657d51b7caa7144c3c2f5ec1c8a1060764b1ef741a

test:
  secret_key_base: c6c3789b1e24e9d5be986e7262647ae796114e0e264cba15442086de8e53631145618900c955c777896ed61a26641af46cd706eade805423496450f401a4e7d0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
